/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * An audio-producing application, exposed to TypeScript.
 *
 * The meaning of `id` is platform specific:
 * - Linux: PipeWire node ID
 * - Windows: process ID (PID)
 * - macOS: process ID (PID); `bundle_id` carries the bundle identifier used
 *   to resolve the ScreenCaptureKit capture target.
 */
export interface AudioApp {
  id: number
  name: string
  processId: number
  bundleId?: string
}

export declare function getAudioApplications(): Array<AudioApp>

export declare function initEngine(): string

/** Returns whether audio capture is currently running. */
export declare function isAudioCaptureActive(): boolean

/** Lists applications that currently produce audio on this platform. */
export declare function listAudioApplications(): Array<AudioApp>

/**
 * Finds the audio application whose name best matches the given label
 * (e.g. a `MediaStreamTrack.label` from `getDisplayMedia` on Wayland).
 * Works on all platforms by matching against the current audio app list.
 */
export declare function resolveAudioAppByName(label: string): AudioApp | null

/**
 * Scans the PipeWire registry for a screen-capture video node created by
 * xdg-desktop-portal and extracts the captured window's application name
 * to auto-detect the correct audio source.  Only meaningful on Wayland;
 * returns `None` on other platforms.
 */
export declare function resolveAudioAppForCapturedWindow(): AudioApp | null

/**
 * Resolves an X11 window ID to its owning application's audio capture
 * target. Uses `_NET_WM_PID` to find the process ID, then looks up the
 * matching `AudioApp` in the PipeWire audio application list.
 *
 * Only meaningful on Linux/X11; returns `None` on other platforms or
 * when the window has no accessible PID property.
 */
export declare function resolveAudioAppForX11Window(windowId: number): AudioApp | null

/**
 * Starts audio capture of a single target application. ONLY the target
 * application's audio is captured; everything else is excluded from the
 * stream (the stream carries the shared window's audio and nothing else).
 *
 * The target identifier is platform specific:
 * - Linux: PipeWire node ID (number; numeric strings are also parsed)
 * - Windows: process ID (number; numeric strings are also parsed)
 * - macOS: bundle identifier (string; a number is resolved via PID lookup)
 */
export declare function startAudioCapture(targetAppId: string | number): boolean

/** Stops the currently running audio capture, if any. */
export declare function stopAudioCapture(): boolean
