/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface AudioApp {
  id: number
  name: string
  processId: number
  bundleId?: string
}

export declare function getAudioApplications(): Array<AudioApp>

export declare function initEngine(): string

export declare function isAudioCaptureActive(): boolean

export declare function listAudioApplications(): Array<AudioApp>

export declare function resolveAudioAppByName(label: string): AudioApp | null

export declare function resolveAudioAppForCapturedWindow(): AudioApp | null

export declare function resolveAudioAppForX11Window(windowId: number): AudioApp | null

export declare function startAudioCapture(targetAppId: string | number): boolean

export declare function stopAudioCapture(): boolean
