[target.'cfg(target_env = "msvc")']
rustflags = [
  "-C", "link-arg=/NODEFAULTLIB:msvcrt",
  "-C", "link-arg=/NODEFAULTLIB:msvcrtd",
  "-C", "link-arg=/NODEFAULTLIB:msvcprt",
  "-C", "link-arg=/NODEFAULTLIB:msvcprtd",
]
