/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface CaptureConfig {
  width: number
  height: number
  fps: number
  videoCodec?: string
}

export declare function captureDmabufFrame(dmabufFd: number, width: number, height: number, pixelFormat: number, timestampLo: number, timestampHi: number): NapiResult<undefined>

export declare function connectLivekitRoom(url: string, token: string): NapiResult<undefined>

export declare function disconnectLivekitRoom(): NapiResult<undefined>

export declare function feedPcm(pcm: Array<number>): NapiResult<undefined>

export declare function getSpectatorCount(): number

export declare function isLivekitRoomConnected(): boolean

export declare function isVideoTrackActive(): boolean

export declare function startVideoTrack(config: CaptureConfig): NapiResult<undefined>

export declare function stopVideoTrack(): NapiResult<undefined>
